# Generated by Django 4.2.5 on 2023-09-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITassistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='Mascara_red',
            field=models.FloatField(null=True),
        ),
    ]
