# Generated by Django 4.2.5 on 2023-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITassistant', '0002_equipos_mascara_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='Porcentaje_RAM',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Porcentaje_disco',
            field=models.FloatField(null=True),
        ),
    ]
