# Generated by Django 4.2.5 on 2023-09-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITassistant', '0004_alter_equipos_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='Mascara_red',
            field=models.TextField(null=True),
        ),
    ]
