# Generated by Django 4.2.5 on 2023-09-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITassistant', '0005_alter_equipos_mascara_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='Capacidad_RAM',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Capacidad_disco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Disponibilidad_RAM',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Disponibilidad_disco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Frecuencia_actual',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Frecuencia_maxima',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Frecuencia_minima',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Porcentaje_RAM',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Porcentaje_disco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Temperatura_actual',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Temperatura_alta',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Temperatura_critica',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Uso_RAM',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='Uso_disco',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
